name: Update advisories

on:
  repository_dispatch:
    types: [ changed ]

jobs:
  update-advisories:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - name: Checkout ruby-advisory-db
        uses: actions/checkout@v6
        with:
          repository: rubysec/ruby-advisory-db
          path: _advisories
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Generate advisories
        run: bundle exec rake advisories:generate
      - name: Get latest advisory commit
        id: git-commit
        working-directory: _advisories
        run: |
          echo "author=$(git show -s --format='%an <%ae>')" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Commit any updates
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated advisory posts against rubysec/ruby-advisory-db@${{ steps.git-commit.outputs.hash }}"
          file_pattern: advisories/_posts/*.md
          commit_user_name: RubySec CI
          commit_user_email: ci@rubysec.com
          commit_author: ${{ steps.git-commit.outputs.author }}
